import HeroArt from '../components/HeroArt'
import Audience from './Audience'
import Process from './Process'
import { projects } from '../data/projects'

const needs = [
 ['Fix an IT problem', 'Get help with computer issues, email, Wi-Fi and everyday systems.', 'IT support'],
 ['Build my website', 'Give people a clear way to discover your organisation and get in touch.', 'Web development'],
 ['Simplify business admin', 'Discuss a portal, application or workflow around the way your team works.', 'Business solutions'],
]
const faqs = [
 ['Can I get help with a one-off problem?', 'Yes. Start with the issue you need to solve, whether it involves one device, an email account or a wider setup. We can discuss the scope before you decide to proceed.'],
 ['Do I need to know exactly what technology I need?', 'No. Tell us what is getting in the way or what you want to achieve. We can help you explore the options and agree a practical next step.'],
 ['How does pricing work?', 'Pricing depends on the work involved. We discuss your requirements and agree the scope and cost before work starts. Include any budget or deadline in your enquiry.'],
 ['Can we discuss ongoing support?', 'Yes. We can discuss maintenance, updates and ongoing help alongside one-off projects, with the scope agreed around your needs.'],
 ['Are GAP TECH software products available now?', 'The product family is currently at the concept stage. You can explore the ideas and register interest, or contact us about a separate custom development project.'],
 ['What happens when I enquire?', 'Share the problem, your current setup and any deadline. We will review your enquiry and discuss the information needed to work out a next step.'],
]
export default function Home() {
 return <>
  <section className="hero"><div><p className="eyebrow">Support. Build. Innovate.</p><h1 className="home-title">Practical IT support and websites <em>for your organisation.</em></h1><p className="hero-text">Help for small businesses, community groups and growing teams. Solve everyday technology problems, build your online presence and simplify the way you work.</p><div className="hero-actions"><a className="button primary" href="/contact">Discuss your project →</a><a className="text-link" href="/it-services">Explore IT support →</a></div><div className="trust-row"><div><strong>Clear advice</strong><span>Understand your options</span></div><div><strong>Practical scope</strong><span>Agree the next step</span></div><div><strong>Personal service</strong><span>Start with your needs</span></div></div></div><HeroArt /></section>
  <section className="services section"><div className="section-heading"><div><p className="eyebrow">What can we help with?</p><h2>Start with what you need.</h2></div><p>From a frustrating IT issue to your next website or business tool.</p></div><div className="service-grid">{needs.map(([title,copy,interest],i) => <article key={title} className={`service-card home-image-card ${i === 0 ? 'featured' : ''}`}><img className="service-card-photo" src={`/images/${['it-support-card','hands-coding-card','products-card'][i]}.jpg`} alt="" width="960" height="640" loading="lazy" decoding="async" /><span className="service-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p><a href={`/contact?interest=${encodeURIComponent(interest)}`}>{['Get IT support','Discuss a website','Discuss your workflow'][i]} →</a></article>)}</div></section>
  <section className="section selected-work"><div className="section-heading"><div><p className="eyebrow">Selected projects</p><h2>Websites built. Organisations supported.</h2></div><p>Website development for four projects, with IT support for Waikato Refugee Forum, Waikato Navigate Trust and Ephata Initiatives Trust.</p></div><div className="work-grid">{projects.map((project, index) => <article className="work-card" key={project.slug}>{project.image && <img className="work-screenshot" src={project.image} alt={`${project.name} homepage screenshot`} loading="lazy" decoding="async" width="1466" height="973" />}<span className="eyebrow">Selected project · 0{index + 1}</span><h3>{project.name}</h3><ul className="work-services" aria-label="Services provided">{project.services.map(service => <li key={service}>{service}</li>)}</ul><p className="work-description">{project.description}</p></article>)}</div><div className="work-enquiry"><p>Need a website, IT support or both? Tell us about your organisation.</p><a className="text-link" href="/contact">Discuss your project →</a></div></section>
  <Audience />
  <section className="section meet-section"><div><p className="eyebrow">Meet GAP TECH</p><h2>Technology starts with a conversation.</h2><p className="page-lead">You should be able to explain what you need in your own words. GAP TECH brings IT support, web development and custom software together, starting with the everyday problems your organisation wants to solve.</p><a className="text-link" href="/about">Get to know our approach →</a></div><div className="approach-panel"><h3>What you can expect</h3><ul><li><strong>Space to explain.</strong> We start with your goals and what is getting in the way.</li><li><strong>Options you can understand.</strong> Clear explanations help you decide what fits.</li><li><strong>An agreed scope.</strong> Discuss the work and cost before getting started.</li></ul></div></section>
  <Process />
  <section className="section faq-section"><p className="eyebrow">Before we get started</p><h2>A few useful answers.</h2><div className="faq-list">{faqs.map(([question,answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
  <section className="section product-teaser"><div><p className="eyebrow">What we’re building</p><h2>Ideas for simpler everyday work.</h2><p>Explore our planned software concepts for support teams, community organisations, property management and education. These products are not yet available.</p></div><a className="text-link" href="/products">Explore the product vision →</a></section>
  <section className="section call-to-action"><div><p className="eyebrow">Let’s find your next step</p><h2>Tell us what you want to fix or build.</h2><p className="cta-note">A short description of your needs is enough to start.</p></div><a className="button primary" href="/contact">Start an enquiry →</a></section>
 </>
}
